# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avi', '0002_remove_tutorialmodel_fib_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialmodel',
            name='resources_cpu_cores',
            field=models.IntegerField(default=1, help_text='Number of CPU cores to be allocated to the AviJob'),
        ),
        migrations.AlterField(
            model_name='tutorialmodel',
            name='resources_ram_mb',
            field=models.IntegerField(default=2000, help_text='Amount of RAM (M) to be allocated for the AviJob'),
        ),
    ]
